sonar.projectKey=todayitsaliha_cohort-9-mern-13118-aliha
sonar.organization=todayitsaliha
sonar.projectName=Scribble-Pal
sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,frontend/tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.html
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.sourceEncoding=UTF-8
