sonar.projectKey=notes-taking-app
sonar.projectName=Note-Taking Web Application
sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,frontend/tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.html
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.sourceEncoding=UTF-8